// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gvesrmjirmepwdisaffi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd2ZXNybWppcm1lcHdkaXNhZmZpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg2OTkxMDEsImV4cCI6MjA1NDI3NTEwMX0.EwkPEi938lZJ5dKksduUtkSMf16Hrw9i80cBnk-1wdc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);